In [1]:
import numpy as np 
mat = np.array([
    [1,2,3],
    [4,5,6]
])
print(mat)

[[1 2 3]
 [4 5 6]]


In [2]:
print(mat.ndim)
print(mat.shape)

2
(2, 3)


In [3]:
print(mat[0,0])
print(mat[1,2])

1
6


In [4]:
print(mat[:,0])
print(mat[:,1])

[1 4]
[2 5]


In [5]:
print(mat*2)

[[ 2  4  6]
 [ 8 10 12]]


In [6]:
m = np.array([
    [10,20],
    [30,40]
])

print(m.shape)
print(m[1,0])
print(m[:,1])
print(m+5)

(2, 2)
30
[20 40]
[[15 25]
 [35 45]]
