In [1]:
import numpy as np 

a = np.zeros(5)
print(a)


[0. 0. 0. 0. 0.]


In [2]:
a.dtype

dtype('float64')

In [3]:
b = np.ones(4)
print(b)

[1. 1. 1. 1.]


In [4]:
z = np.zeros((2,3))
o = np.ones((3,2))

print(z)
print(o)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr2 = np.arange(0,10,2)
print(arr2)

[0 2 4 6 8]


In [8]:
a = np.arange(1,7)
print(a)
b = a.reshape(2,3)
print(b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [9]:
print(b.shape)

(2, 3)


In [10]:
x = np.arange(1,13)
y = x.reshape(3,4)

print(y)
print(y.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
