In [1]:
import numpy  as np 
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
lst = [1,2,3]
print(lst*2)
print(a*2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
print(a.ndim)
print(a.shape)
print(a.dtype)

1
(3,)
int64


In [ ]:
print(a[0]) #first element
print(a[1]) 

1
2


In [ ]:
print(a[0:2])


[1 2]


In [ ]:
b = np.array([5,10,15])
print(b*3)
print(b[1])

[15 30 45]
10
