In [2]:
import numpy as np 

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
print(a+1)
print(a*2)

[2 3 4]
[2 4 6]


In [4]:
b = np.array([4,5,6])
print(a+b)
print(a*b)

[5 7 9]
[ 4 10 18]


In [5]:
print(a**2)

[1 4 9]


In [6]:
print(b/2)

[2.  2.5 3. ]


In [7]:
mat = np.array([
    [1,2],
    [3,4]
])
print(mat+10)
print(mat*2)

[[11 12]
 [13 14]]
[[2 4]
 [6 8]]
