In [1]:
import numpy as np 
mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(mat[1,:])

[4 5 6]


In [4]:
print(mat**2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [5]:
for i in range(len(mat)):
    total = 0
    for j in mat[:,i]:
        total += j
    print(total/len(mat))


4.0
5.0
6.0


In [7]:
column_mean = mat.mean(axis=0)
print(column_mean)

[4. 5. 6.]


In [8]:
print(mat.mean(axis=0))

[4. 5. 6.]
