In [8]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
brr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(type(arr))

(6,)
1
int64
<class 'numpy.ndarray'>


In [56]:
arr = np.arange(1,21)
print(arr)
arr = arr.reshape((4,5))
print(arr)
arr = arr.reshape(-1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [54]:
print(arr[0:3])
print(arr[-2:])
print(arr[2::2])

[1 2 3]
[19 20]
[ 3  5  7  9 11 13 15 17 19]


In [55]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]
               ])
print(mat[1,:])
print(mat[:,0])
print(mat[2,:])

[4 5 6]
[1 4 7]
[7 8 9]
